### ISSUE TITLE
[ux] Deleting an OrganizationUser raises exception

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-users#169] opened 2020-08-23 20:04 UTC
Deleting an OrganizationUser which is also an OrganizationOwner raises exception. But, this exception is not handled properly and throws error on user.
![Screenshot_20200824_013032](https://user-images.githubusercontent.com/32094433/90987552-6a11b300-e5a9-11ea-8fac-397559bbbd03.png)

Instead of throwing this error which user will definitely not see in production, send an error message to UserAdmin page.

**Comment by nemesisdesign** [comment] 2020-08-23 22:15
Duplicate of https://github.com/openwisp/openwisp-users/issues/165

**Closed by nemesisdesign** 2020-08-23 22:15 UTC
